server:
  port: 9999
spring:
  cloud:
    config:
      server:
        git:
          uri: git@gitee.com:rogersnow/springconfigcenter.git
rabbitmq:
  host: localhost
  port: 5672
  password: guest
  username: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"
